# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0349b3605daf44812e462f4b9d713c118414cd04df86365e0a7f746f0b6baa1aae5648ad353cde0d0ee5e08e8d8d88f6e456726e811fabd46d403899ceb29d88

test:
  secret_key_base: 70a4ef900325f53a11c461353813a0beb19d7a3e5e114bb523e3207937c106ecbf32821b7322c59818067044cf21885a551f797e8ab4806a1c5704f4583274c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
